add_newline = true

#format = """
#[ash@void](bold red) [on](bold white) $directory
#[âœ¦ Â»](blue) """

[time]
disabled = true
format = '[$time]($style) '
time_format = "%I:%M"

[line_break]
disabled=false

[character]
success_symbol="[Â»](blue)"
error_symbol="[Â»](blue)"

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "ó°¢Ÿ "
discharging_symbol = "ó±ƒ "

[[battery.display]]
threshold = 20
style = "red"

[hostname]
ssh_only = false
format =  "[ash@void](bold red) [on](bold white) "
trim_at = ".companyname.com"
disabled = false

[aws]
symbol = "îŒ½ "
disabled = false

[lua]
disabled = false

[cmake]
symbol = "cmake"
disabled = false

[conda]
symbol = "ï„Œ "
disabled = false

[dart]
symbol = "î˜ "
disabled = false

[directory]
home_symbol = "ï€• "
read_only = " ï€£ "
style = "bold blue"
truncation_length = 2
truncation_symbol = "./"

[elixir]
symbol = "î‰µ "
disabled = false

[elm]
symbol = "î˜¬ "
disabled = false

[git_branch]
symbol = "ó°Š¢  "
format="[on](bold white) [$symbol$branch]($style) "

[golang]
symbol = "î˜§ "
disabled = false

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "
disabled = true

[julia]
symbol = "î˜¤ "
disabled = false

[memory_usage]
disabled = true
format = "[via ](bold white)[${ram}]($style) "
threshold = -1
style = "bold green"

[nim]
symbol = "ïš¤ "
disabled = false

[nix_shell]
symbol = "ï‹œ "
disabled = false

[nodejs]
symbol = "î‰ "
disabled = false

[package]
symbol = "ï£– "
disabled = false

[perl]
symbol = "î© "
disabled = false

[php]
symbol = "î˜ˆ "
disabled = false

[python]
symbol = "î˜† "
disabled = true

[ruby]
symbol = "îˆ¾ "
disabled = false

[rust]
symbol = "î¨ "
disabled = false

[swift]
symbol = "ï¯£ "
disabled = false

[status]
style = ""
symbol = ""
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = false
disabled = true
